### ISSUE TITLE
"No space left on device"

### ISSUE THREAD

**Issue by Y0HO** [dessalines/flowchat#141]
No user created discussions/threats/content are loaded.
I think the problem is that every visitor gets an cookie and that every anonymous user/visitor is stored in the database and now the drive is full.
Error:
`org.postgresql.util.PSQLException: ERROR: could not extend file "base/16385/17009": No space left on device Hint: Check free disk space., query: INSERT INTO user_ (name) VALUES (?), params: 1asslcba7qmdssqni3q07dh2o7504om8llp041tomvn1etfpn6cr`

A solution could be to delete the cookies or anonymous users after a week.

**Comment by dessalines** [comment]
Sorry about that, this problem should be fixed now.
