### ISSUE TITLE
Posts are shown more than once

### ISSUE THREAD

**Issue by Y0HO** [dessalines/flowchat#163]
Posts are shown more than once, especially if you scroll down.
![untitled](https://user-images.githubusercontent.com/37078024/39642679-c2027190-4fd2-11e8-9109-a524614a5245.png)

they have the same discussion number/ID so they are not just reposts. (i zoomed out of it so you can see all 3 but it was the same in normal zoom)
also its very buggy and laggy if you scroll down a long time espacially if you use the middle click.
Maybe after 100 posts it would be good to link to a page2 or so.

**Comment by dessalines** [comment]
True, I don't have any limitations on the infinite scrolling yet, this would be a wishlist item. The repeated post is a bug that I'll have to look into.

**Comment by dessalines** [comment]
This should be fixed now, I've done away with the cards that caused this issue.
