### ISSUE TITLE
Image upload

### ISSUE THREAD

**Issue by faljse** [dessalines/flowchat#164]
Hi,
im thinking about using flowchat as some kind of blog.
One thing i really would like to have then is local image uploads/hosting.

What would be the most sane way to add this feature to flowchat?

**Comment by dessalines** [comment]
I don't plan on making flowchat an image host, at least until it gets an active community. For most of reddits history for example, it used external image hosts like imgur. Image hosting would balloon hosting costs to a level that doesn't make sense right now.
