### ISSUE TITLE
New install won't load in browser. err_content_decoding_failed is returned by the browser

### ISSUE THREAD

**Issue by lordnothing** [dessalines/flowchat#207]
I set up flowchat via the docker-compose instructions and cannot access the page after starting the containers. links(1) and Falkon both return with content decoding errors. I've tried via http://localhost:4567 and a reverse proxy on a domain that I own. Both methods have the same error.

**Comment by dessalines** [comment]
Let me double check and try mine.

**Comment by dessalines** [comment]
For the docker install, what are you using for your `ARG ENDPOINT_NAME` ? 

Try setting a non-https endpoint name, and accessing with MY_IP:4567 . Then we can at least verify that its an nginx issue.

I noticed on my nginx I needed to add websocket support, was surprised it didn't have it out of the box, i had to add it: https://stackoverflow.com/questions/12102110/nginx-to-reverse-proxy-websockets-and-enable-ssl-wss#14969925

```
    # WebSocket support
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
```

**Comment by lordnothing** [comment]
I left `ARG ENDPOINT_NAME` `http://localhost:4567` and tried accessing it from links(1) on the VPS. 

I’ll try adding the websocket stuff to the reverse proxy later today and see what happens.

**Comment by lordnothing** [comment]
Dockerfile:
```
FROM node:9 as node-builder

# Hacky workaround for installing @angular/cli
# RUN chmod a+w /usr/local/lib/node_modules && chmod a+w /usr/local/bin
# USER node
# RUN npm i -g @angular/cli@latest

# Build front end resources
USER root
ARG UI_PATH=/opt/flowchat/ui
COPY ui ${UI_PATH}
WORKDIR ${UI_PATH}

ARG ENDPOINT_NAME=http://localhost:4567
RUN echo "ENDPOINT_NAME is ${ENDPOINT_NAME}"
RUN echo "export const environment = {production: true,endpoint: '${ENDPOINT_NAME}/',websocket: 'ws`echo ${ENDPOINT_NAME}|cut -b 5-999`/poll'};" > src/environments/environment.prod.ts
RUN cat src/environments/environment.prod.ts
RUN yarn
RUN yarn build --prod --aot


FROM maven:3.5-jdk-8 as java-builder

COPY service /opt/flowchat/service
COPY --from=node-builder /opt/flowchat/ui/dist /opt/flowchat/service/src/main/resources

WORKDIR /opt/flowchat/service
RUN mvn clean install -DskipTests -Dliquibase.skip

FROM openjdk:8-jre-slim

COPY --from=java-builder /opt/flowchat/service/target/flowchat.jar /opt/flowchat.jar
```

I don't think I changed anything there...

**Comment by lordnothing** [comment]
So, I tried accessing it via `links http://127.0.0.1:4567` and got the 'unable to decompress with zlib' error, but the page links loads behind the dialog is a jetty 404 that says:
![screenshot_20181010_001000](https://user-images.githubusercontent.com/2688589/46716368-f36fa480-cc20-11e8-8cd7-f85bd298eac2.png)

**Comment by dessalines** [comment]
Okay, I've made a commit removing the gzip header: https://github.com/dessalines/flowchat/commit/d3ce9d54e147fd23ad0d8e5da500639f8e4e2893 , lets see if thats it. 

run:
```
git pull
docker-compose build --no-cache
docker-compose up
```

**Comment by lordnothing** [comment]
I’ll try later this evening and let you know how it goes.

**Comment by lordnothing** [comment]
Still no root document. It seems something may be wrong with the front end setup.
![c380143d-e019-40f7-9525-4a5b176d1174](https://user-images.githubusercontent.com/2688589/46755119-80e2e100-cc81-11e8-81ea-26b4209cac43.jpeg)

**Comment by dessalines** [comment]
Wait, this is a different error than before, I though it was `err_content_decoding_failed` ?

**Comment by lordnothing** [comment]
It’s the same error. The 404 was just hidden behind the gzip problem.

**Comment by dessalines** [comment]
This is super difficult because I can't replicate it on my machine. I looked into this a little more and discovered it may have been an issue with the web server (spark), I've updated it just now, run these below again:

```
git pull
docker-compose build --no-cache
docker-compose up
```

**Comment by lordnothing** [comment]
The gzip problem returned, so I can’t tell if the 404 went away. All I did was follow the Docker instructions and have tried various values for ENDPOINT in the Dockerfile.

**Comment by dessalines** [comment]
Okay I finally installed a virtualbox ubuntu to replicate the error, and I think its fixed now. Run:
```
git pull
docker-compose up --build
```
